import '../models/product_model.dart';

class LocalProducts {
  static final List<Product> featured = [
    Product(
      id: 1001,
      title: 'Samsung 65-Inch Neo QLED 4K Smart TV QA6...',
      description: 'Samsung 65-Inch Neo QLED 4K Smart TV with Quantum Matrix Technology and Neural Quantum Processor.',
      price: 657.98,
      discountPercentage: 0,
      rating: 4.5,
      stock: 10,
      brand: 'Samsung',
      category: 'TVs',
      thumbnail: '',
      images: [],
      localImage: 'assets/images/samsung_tv.png',
    ),
    Product(
      id: 1002,
      title: 'Apple 2025 MacBook Air 13-inch Laptop with...',
      description: 'Apple MacBook Air 13-inch with M4 chip, 16GB RAM, 256GB SSD.',
      price: 1020.0,
      discountPercentage: 0,
      rating: 4.5,
      stock: 5,
      brand: 'Apple',
      category: 'Laptops',
      thumbnail: '',
      images: [],
      localImage: 'assets/images/macbook_air.png',
    ),
    Product(
      id: 1003,
      title: 'POLAR Ignite 3 GPS Smartwatch iPhone ...',
      description: 'Polar Ignite 3 GPS Smartwatch with advanced sleep tracking and fitness features.',
      price: 390.0,
      discountPercentage: 0,
      rating: 4.5,
      stock: 15,
      brand: 'POLAR',
      category: 'Smartwatches',
      thumbnail: '',
      images: [],
      localImage: 'assets/images/Watch.png',
    ),
    Product(
      id: 1004,
      title: 'Soundcore by Anker Life Q30 Hybrid Active Noise...',
      description: 'Soundcore Q30 Hybrid Active Noise Cancelling Headphones with Hi-Res Sound.',
      price: 79.0,
      discountPercentage: 0,
      rating: 4.5,
      stock: 30,
      brand: 'Anker',
      category: 'Headphones',
      thumbnail: '',
      images: [],
      localImage: 'assets/images/Soundcore_Headphone.png',
    ),
    Product(
      id: 1005,
      title: 'HONOR 400 5G Smartphone, 200MP AI ...',
      description: 'HONOR 400 5G Smartphone with 200MP AI Camera and 6.7-inch AMOLED display.',
      price: 440.0,
      discountPercentage: 0,
      rating: 4.5,
      stock: 20,
      brand: 'HONOR',
      category: 'Smartphones',
      thumbnail: '',
      images: [],
      localImage: 'assets/images/honor_phone.png',
    ),
    Product(
      id: 1006,
      title: 'JBL Go 4 Portable Bluetooth Speaker with l...',
      description: 'JBL Go 4 Portable Bluetooth Speaker, IP67 waterproof and dustproof.',
      price: 37.98,
      discountPercentage: 0,
      rating: 4.5,
      stock: 50,
      brand: 'JBL',
      category: 'Speakers',
      thumbnail: '',
      images: [],
      localImage: 'assets/images/Jbl.png',
    ),
  ];

  static final Map<int, double> egpPrices = {
    1001: 32899,
    1002: 51000,
    1003: 19500,
    1004: 3950,
    1005: 21999,
    1006: 1899,
  };
}
